### PR TITLE
Update to ShellCheck v0.5.0

### PR DESCRIPTION
**Pull request by wilson**
Everything seems to work nicely after rebuilding the image.
Please let me know if I missed anything.

### CODE REVIEW

**Comment by mcfilib** [comment]
Nice one, @wilson! 

Any chance you could also update [data/env.yml](https://github.com/mcfilib/codeclimate-shellcheck/blob/master/Makefile#L5)? If new checks have been added to SC, this is how the associated textual explanation makes it way into the engine.

**Comment by wilson** [comment]
I struggled with that a bit; couldn't get the make task to execute.
However, I did just get it working.. I had to make this change to the prepare.rb script though:
```
diff --git a/data/prepare.rb b/data/prepare.rb
index a36ffcb..7540823 100755
--- a/data/prepare.rb
+++ b/data/prepare.rb
@@ -39,7 +39,9 @@ old_env = YAML.load(File.read('env.yml'))
 
 # IO ()
 old_env.each do |key, val|
-  new_env[key]['remediation_points'] = val['remediation_points']
+  if (new_val = new_env[key])
+    new_val['remediation_points'] = val['remediation_points']
+  end
 end
 
 # String
```

I guess not everything has remediation points. Should I make a PR for that change, or did I mess it up by allowing it to proceed?

Thanks!

**Comment by mcfilib** [comment]
I’m not sure off the top of my head and I’m away from my computer until Monday. You might have to dig into the Haskell source if you’re feeling brave!

**Comment by mcfilib** [comment]
@dgattey not until we know whether or not the ruby script/remediation point issue raised above is a breaking chance.

i don’t have any time to do this at the moment, so feel free to investigate yourself and let me know.

**Comment by mcfilib** [comment]
ping @pbrisbin @wfleming. are you able to help out?

**Comment by mcfilib** [comment]
superceded by https://github.com/mcfilib/codeclimate-shellcheck/pull/65

**Pull request closed without merging**
